version: "3"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64

    image: test_9
    container_name: test_9_api
    ports:
      - "8000:8000"
    env_file: ".env" 
    depends_on:
      - database 


  database:
    image: "postgres:16"
    container_name: test_9_database
    env_file: ".env"
    ports:
      - "5432:5432"