version: "3"

services:
  api:  &app
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64

    image: test_9
    container_name: test_9_api
    ports:
      - "8000:8000"
    env_file: ".env" 
    depends_on:
      - database
      - mailing
      - broker 
      - cache
    volumes:
      - "./:/app"

  database:
    image: "postgres:16"
    container_name: test_9_database
    env_file: ".env"
    volumes:
      - pg_data:/var/lib/postgresql/data

  broker:
    image: "redis:latest"
    container_name: test_9_broker
    ports:
      - "6379:6379"

  cache:
    image: "redis:latest"
    container_name: test_9_cache
    ports:
      - "6380:6379"

  mailing:
    image: "mailhog/mailhog:latest"
    container_name: test_9_mail
    env_file: ".env"
    ports:
      - "8025:8025"

  worker:
    <<: *app
    container_name: test_9_worker
    ports: []
    entrypoint: bash
    command: -c "watchmedo auto-restart --pattern='*.py' --recursive -- celery -A config worker -l INFO"


volumes:
  pg_data: {} 