# Generated by Django 4.2.11 on 2024-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("juni_id", models.IntegerField(max_length=5)),
                ("seni_id", models.IntegerField(max_length=5)),
                ("title", models.CharField(max_length=50)),
                ("body", models.TextField(max_length=100)),
            ],
        ),
    ]
